server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/joker_monster/sringcloud-config.git #https的，不是git的
#通过 config-server可以连接到git,访问其中的资源以及配置



